### ISSUE TITLE
Cloned eduacass-ui and need some help

### ISSUE THREAD

**Issue by mkscala** [dalareo/educaas-ui#4]
I have created executed the below, how do i login to the UI, Is the below commands correct ?

root@a278af8270ff:/opt# bash -c "/env/bin/python /app/manage.py create_db"
root@a278af8270ff:/opt# bash -c "/env/bin/python /app/manage.py db init"
DEBUG:root:{'Course Template': '/opt/docker-compose-projects/Course Template', 'Blog': '/opt/docker-compose-projects/Blog', 'Chat': '/opt/docker-compose-projects/Chat', 'Library': '/opt/docker-compose-projects/Library'}
  Creating directory /opt/migrations ... done
  Creating directory /opt/migrations/versions ... done
  Generating /opt/migrations/README ... done
  Generating /opt/migrations/alembic.ini ... done
  Generating /opt/migrations/env.py ... done
  Generating /opt/migrations/env.pyc ... done
  Generating /opt/migrations/script.py.mako ... done
  Please edit configuration/connection/logging settings in '/opt/migrations/alembic.ini' before proceeding.
root@a278af8270ff:/opt# bash -c "/env/bin/python /app/manage.py db migrate"
DEBUG:root:{'Course Template': '/opt/docker-compose-projects/Course Template', 'Blog': '/opt/docker-compose-projects/Blog', 'Chat': '/opt/docker-compose-projects/Chat', 'Library': '/opt/docker-compose-projects/Library'}
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.ddl.postgresql] Detected sequence named 'users_id_seq' as owned by integer column 'users(id)', assuming SERIAL and omitting
INFO  [alembic.env] No changes in schema detected.

**Comment by mkscala** [comment]
Also When I tried the Blog I got the below error
educaas_ui_1 | DEBUG:root:get project /opt/docker-compose-projects/Blog
educaas_ui_1 | DEBUG:compose.config.config:Using configuration files: /opt/docker-compose-projects/Blog/docker-compose.yml
educaas_ui_1 | DEBUG:docker.auth.auth:File doesn't exist
educaas_ui_1 | DEBUG:root:ps blog
educaas_ui_1 | DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dblog%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
educaas_ui_1 | DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=0&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dblog%22%2C+%22com.docker.compose.oneoff%3DTrue%22%5D%7D&size=0 HTTP/1.1" 200 3
educaas_ui_1 | INFO:werkzeug:172.17.0.1 - - [02/May/2016 01:46:31] "GET /api/v1/projects/Blog HTTP/1.1" 200 -
educaas_ui_1 | INFO:werkzeug:172.17.0.1 - - [02/May/2016 01:46:31] "GET /api/v1/host HTTP/1.1" 200 -
educaas_ui_1 | INFO:werkzeug:172.17.0.1 - - [02/May/2016 01:46:44] "GET /api/v1/projects/yml/Blog HTTP/1.1" 200 -
educaas_ui_1 | DEBUG:root:get project /opt/docker-compose-projects/Blog
educaas_ui_1 | DEBUG:compose.config.config:Using configuration files: /opt/docker-compose-projects/Blog/docker-compose.yml
educaas_ui_1 | DEBUG:docker.auth.auth:File doesn't exist
educaas_ui_1 | DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dblog%22%2C+%22com.docker.compose.service%3Ddb%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
educaas_ui_1 | DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dblog%22%2C+%22com.docker.compose.service%3Dwordpress%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
educaas_ui_1 | INFO:werkzeug:172.17.0.1 - - [02/May/2016 01:47:04] "POST /api/v1/start HTTP/1.1" 200 -
educaas_ui_1 | DEBUG:root:get project /opt/docker-compose-projects/Blog
educaas_ui_1 | DEBUG:compose.config.config:Using configuration files: /opt/docker-compose-projects/Blog/docker-compose.yml
educaas_ui_1 | DEBUG:docker.auth.auth:File doesn't exist
educaas_ui_1 | DEBUG:root:ps blog
educaas_ui_1 | DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dblog%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
educaas_ui_1 | DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=0&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dblog%22%2C+%22com.docker.compose.oneoff%3DTrue%22%5D%7D&size=0 HTTP/1.1" 200 3
educaas_ui_1 | INFO:werkzeug:172.17.0.1 - - [02/May/2016 01:47:04] "GET /api/v1/projects/Blog HTTP/1.1" 200 -
educaas_ui_1 | INFO:werkzeug:172.17.0.1 - - [02/May/2016 01:49:44] "GET /api/v1/status HTTP/1.1" 200 -
educaas_ui_1 | INFO:werkzeug:172.17.0.1 - - [02/May/2016 01:49:44] "GET /api/v1/host HTTP/1.1" 200 -
educaas_ui_1 | DEBUG:root:get project /opt/docker-compose-projects/Chat
educaas_ui_1 | DEBUG:compose.config.config:Using configuration files: /opt/docker-compose-projects/Chat/docker-compose.yml
educaas_ui_1 | DEBUG:docker.auth.auth:File doesn't exist
educaas_ui_1 | DEBUG:root:ps chat
educaas_ui_1 | DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=1&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dchat%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&size=0 HTTP/1.1" 200 3
educaas_ui_1 | DEBUG:requests.packages.urllib3.connectionpool:"GET /v1.21/containers/json?all=0&limit=-1&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dchat%22%2C+%22com.docker.compose.oneoff%3DTrue%22%5D%7D&size=0 HTTP/1.1" 200 3
educaas_ui_1 | INFO:werkzeug:172.17.0.1 - - [02/May/2016 01:49:44] "GET /api/v1/projects/Chat HTTP/1.1" 200 -

**Comment by dalareo** [comment]
Hi @mkscala, the first log is the normal behaviour, no error is thrown. 
In order to log in you have to visit 0.0.0.0:5000 and register first. 
No error as well is noticed on the second log.

**Comment by mkscala** [comment]
I logged In and registered first but not able to create the containers , once i click the start button , it says project started but i don't see any containers running

**Comment by dalareo** [comment]
In order to deploy containers you have to click UP

**Comment by mkscala** [comment]
Any plans to update to Nginx to serve Static files and Gunicorn Webserver to replace the dev flask werkzeug: websever ?

**Comment by mkscala** [comment]
Also the data is getting lost in the container exited. 
Do you have plans to create a seperate data container Using the container volumes
https://docs.docker.com/engine/examples/postgresql_service/
You can use the defined volumes to inspect the PostgreSQL log files and to backup your configuration and data:
$ docker run --rm --volumes-from pg_test -t -i busybox sh

**Comment by dalareo** [comment]
Yes, of course @mkscala, this is just WIP!! Feel free to contribute!!
The first (important) step is creating an updated README.md!!
